name: Run MLflow Project

on:
  workflow_dispatch:

jobs:
  run-mlflow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Debug project structure
        run: |
          echo "CURRENT DIR: $(pwd)"
          ls -al
          echo "---- MLProject folder ----"
          ls -al MLProject

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: workflow_env
          environment-file: ${{ github.workspace }}/MLProject/conda.yaml
          python-version: 3.10

      - name: Install MLflow
        run: pip install mlflow

      - name: Run MLflow Project
        run: mlflow run ${{ github.workspace }}/MLProject
